on: [push, pull_request]

name: Testing

jobs:


  test:
    name: Compiler Cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Install Toolchain
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Testing modules
        run: |
          cd compiler/crashc
          cargo test
          cd ../crashc-lexer
          cargo test
