on: [push, pull_request]

name: Testing

jobs:
  check:
    name: Compiler Cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

  test:
    name: Compiler Cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Install Toolchain
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Testing modules
      - working-directory: ./compiler/crashc
        run: cargo test